name: allsql
description: AllSQL is an open-source compact browser based SQL Compiler, built using Flutter.

publish_to: 'none'

version: 1.1.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite_web:
    git:
      url: https://github.com/deakjahn/sqflite_web.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3

flutter:

  uses-material-design: true
